### ISSUE TITLE
Get User's Playlists Is Missing

### ISSUE THREAD

**Issue by WestheadJ** [spotipy-dev/spotipy-examples#1]
# Get User's Playlist Is Missing

In the notebook's 'summary' it states under [Playlists](https://github.com/spotipy-dev/spotipy-examples/blob/634e91e8537da3d4cc703d4121e363e9e616718c//#Playlists) there is a section called 'Get Current User's Playlists'
Screenshot Evidence:
<img width="351" alt="Screenshot 2023-02-02 at 8 49 45 pm" src="https://user-images.githubusercontent.com/57768613/216446338-234a1ba3-b480-4683-8246-1d839ab5c439.png">

However if you go to the playlist section, it isn't to be found
Screenshot Evidence:
<img width="708" alt="Screenshot 2023-02-02 at 8 51 18 pm" src="https://user-images.githubusercontent.com/57768613/216446625-3a43aa1e-5d12-47ae-b175-3ccdc892cc4d.png">

**Comment by mase-git** [comment]
We are working to complete the notebook from the missing sections. I have pushed an updated version of the notebook with the insertion of the titles of the still unfinished sections so that we can make the notebook consistent with the structure of the summary. 

If you are interested, you could also do some PRs and add some missing examples yourself. 

Thanks again for the report!

**Comment by WestheadJ** [comment]
Okay than you no worries, if I get time I may create some PRs
